services:
  nakas.dev:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nakas.dev 
    restart: unless-stopped
    environment:
      - PORT=8080
    networks:
      - public


networks:
  public:
    external: true
    name: public
